name: Static analysis

on:
  pull_request:
    types: [opened, synchronize, reopened]

  workflow_run:
    workflows: ['Compress images']
    types: [completed]

jobs:
  statics:
    name: Static analysis
    uses: monicahq/workflows/.github/workflows/static.yml@v2
    with:
      php-version: 8.2
