name: Unit tests

on:
  push:
    branches:
      - main
      - next
      - next-major
      - beta
      - alpha
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    types:
      - created

  workflow_run:
    workflows: ['Compress images']
    types: [completed]

jobs:
  tests:
    uses: monicahq/workflows/.github/workflows/library.yml@init
    with:
      php-version: ${{ matrix.php-version }}
      laravel-version: ${{ matrix.laravel-version }}
      coverage: ${{ matrix.php-version == '8.2' && matrix.laravel-version == '10.*' }}
      sonar_project: asbiin_laravel-adorable
      sonar_organization: asbiin-github

    strategy:
      fail-fast: false
      matrix:
        php-version: [8.0, 8.1, 8.2]
        laravel-version: [8.*, 9.*, 10.*]
        exclude:
          - php-version: 8.0
            laravel-version: 10.*
