name: Unit tests

on:
  push:
    branches:
      - main
      - next
      - next-major
      - beta
      - alpha
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    types:
      - created

  workflow_run:
    workflows: ['Compress images']
    types: [completed]

env:
  default-php-version: '8.0'
  default-laravel-version: '8.*'


jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: [7.4, 8.0]
        laravel-version: [8.*]
        composer_flags:  ['', '--prefer-lowest']
    name: PHP ${{ matrix.php-version }} | Laravel ${{ matrix.laravel-version }} ${{ matrix.composer_flags }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
          extension-csv: sqlite, gmp
      - name: Check PHP Version
        run: php -v
      - name: Check Composer Version
        run: composer -V
      - name: Check PHP Extensions
        run: php -m

      - name: Validate composer.json
        run: composer validate

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer files
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer1-${{ hashFiles('**/composer.json') }}-${{ matrix.php-version }}-${{ matrix.laravel-version }}-${{ matrix.composer_flags }}
          restore-keys: |
            ${{ runner.os }}-composer1-${{ hashFiles('**/composer.json') }}-${{ matrix.php-version }}-${{ matrix.laravel-version }}-${{ matrix.composer_flags }}
            ${{ runner.os }}-composer1-${{ hashFiles('**/composer.json') }}-${{ matrix.php-version }}-${{ matrix.laravel-version }}
            ${{ runner.os }}-composer1-${{ hashFiles('**/composer.json') }}-${{ matrix.php-version }}
            ${{ runner.os }}-composer1-${{ hashFiles('**/composer.json') }}
            ${{ runner.os }}-composer1-

      - name: Install dependencies with Laravel ${{ matrix.laravel-version }}
        run: |
          export COMPOSER_ROOT_VERSION=dev-master
          composer require "laravel/framework:${{ matrix.laravel-version }}" --no-interaction --no-progress --prefer-stable --prefer-dist ${{ matrix.composer_flags }}

      - name: Run test suite
        run: phpdbg -dmemory_limit=4G -qrr vendor/bin/phpunit -c phpunit.xml --log-junit ./results/results.xml --coverage-clover ./results/coverage.xml

      - name: Fix results files
        run: sed -i -e "s%$GITHUB_WORKSPACE/%%g" *.xml
        working-directory: results

      - name: Store results
        if: matrix.php-version == env.default-php-version && matrix.laravel-version == env.default-laravel-version && matrix.composer_flags == ''
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: results


  ####################
  # Sonarcloud
  ####################
  reporting:
    name: SonarCloud Scan
    needs: tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [8.0]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download results
        uses: actions/download-artifact@v2
        with:
          name: results
          path: results

      - name: SonarCloud Scan
        if: env.SONAR_TOKEN != ''
        uses: SonarSource/sonarcloud-github-action@v1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


  ####################
  # Semantic release
  ####################
  semantic-release:
    needs: tests
    runs-on: ubuntu-latest
    name: Semantic release
    if: github.event_name != 'pull_request'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Get all tags

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN_RELEASE: ${{ secrets.GH_TOKEN_RELEASE }}
        with:
          semantic_version: 17.3.7
          extra_plugins: |
            @semantic-release/changelog
            semantic-release-github-pullrequest

      - name: New release published
        if: steps.semantic.outputs.new_release_published == 'true'
        run: echo ${{ steps.semantic.outputs.new_release_version }}

      - name: Store changelog file
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: changelog
          path: CHANGELOG.md
